apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: A frontend React application for ${{ values.name }}
  tags:
    - react
    - frontend
spec:
  type: website
  lifecycle: experimental
  owner: user:guest
